userservice:
  mail:
    created:
      subject: "Аккаунт создан"
      message: "Здравствуйте! Ваш аккаунт на сайте ваш сайт был успешно создан."
    deleted:
      subject: "Аккаунт удален"
      message: "Здравствуйте! Ваш аккаунт был удалён."

spring:
  application:
    name: aston-hibernate

  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false

kafka:
  topic:
    notification: aston-notification

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

  level:
    root: info                    # Основной уровень логирования
    org.hibernate: error          # Hibernate (общий уровень)
    org.hibernate.SQL: error      # SQL-запросы Hibernate
    org.hibernate.type.descriptor.sql.BasicBinder: trace  # Параметры запросов

springdoc:
  show-actuator: true