spring:
  application:
    name: aston-hibernate

  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

  level:
    root: info                    # Основной уровень логирования
    org.hibernate: error          # Hibernate (общий уровень)
    org.hibernate.SQL: error      # SQL-запросы Hibernate
    org.hibernate.type.descriptor.sql.BasicBinder: trace  # Параметры запросов